const enValidationErrors = {
  'is_not_rtl_language_code': 'ليست لغه من اليمين الي اليسار',
  'is_not_ltr_language_code': 'ليست لغه من اليسار الي اليمين',
  'is_not_valid': 'غير صحيح',
  'is_not_port': 'ليس رقم منفذ صحيح',
  'required': 'required',
  'min_length': 'يجب الحد الادنى لطول النص :min',
  'max_length': 'الحد الاقصي لطول هذا النص :max',
  'range_length': 'الحد المسموح به لطول النص اقل من :max واكبر من :min',
  'is_not_email_address': 'not valid email address',
  'is_not_bool': 'ليس متغير بولين.',
  'is_not_date_format': 'ليس تاريخ صحيح',
  'is_not_date_millis': 'ليست ملي ثانية صحيح',
  'is_not_hex_color': 'ليس لون هيكس صحيح.',
  'is_not_after_date': 'يجب ان يكون بعد :date',
  'must_contains_any': 'يجب ان يحتوي علي :list',
  'not_contains': 'يجب ان يحتوي علي :value',
  'must_not_contains_any': 'يجب ان لا يحتيو علي اي من  :list',
  'must_be_in_list': 'يجب ان يكون من ضمن :list',
  'must_not_be_in_list': 'يجب ان لا يكون من ضمن :list',
  'must_be_num': 'يجب ان يتكون من ارقام فقط',
  'must_be_int': 'يجب ان يكون رقم صحيح',
  'must_be_max': 'يجب ان تكون اكبر قيمه :maxNum',
  'must_be_min': 'يجب ان تكون اقل قيمه :minNum',
  'is_egyptian_num': 'يجب ان يكون رقم هاتف مصري',
  'is_it_contains': 'يجب ان يحتوي علي :value',
  'must_end_with': 'يجب ان ينتهي بـ :value',
  'is_empty': 'يجب ان يكون فارغ',
  'should_match': 'يجب ان يكون مطابق لـ :value1',
  'starts_with': 'يجب ان يبدا بـ  :value',
  'not_valid_date_millis': 'not_valid_date_millis',
  'is_ksa_num': 'It must be a Saudi number',
  'not_valid_url': 'This is not a valid url',
  'not_valid_facebook_url': 'This is not facebook url',
  'not_valid_youtube_url': 'This is not youtube url'
};
